sequenceDiagram
MySpace->>Facebook: Umm... these people are doing cool things
loop Check
    Facebook->>Facebook: How to do better?
end
Note right of Facebook: Rational thoughts!
Facebook-->>MySpace: formalize and fix the users' concerns